name: pokedex_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^19.0.0
  fluttertoast: ^8.2.12
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  provider: ^6.1.2
  riverpod: ^2.6.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
